teleop_twist_joy:
  ros__parameters:
    enable_button: -1 #ปิดการใช่งานปุ่ม
    axis_linear:
      x: 1 #ใช้Analog ของ Xbox ในการควบคุม
    scale_linear:
      x: 1.3
    scale_linear_turbo:
      x: 2.5
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 2.5
    require_enable_button: false
    enable_turbo_button: 5
